# https://vim-jp.org/vimdoc-ja/quickfix.html#error-file-format
version: 2
root-markers:
  - .git/
tools:
  text-textlint: &text-textlint
    lint-stdin: false
    lint-command: 'deno run --allow-sys --allow-env --allow-run --allow-read ~/.local/share/deno_ts/textlint.ts ${INPUT}'
    lint-ignore-exit-code: true
    lint-formats:
      - "%f:%l:%c: %m [%trror/%r"
      - "%E%f:%l:%c: %m"
      - "%C%r"
      - "%Z [%trror/%r"
    root-markers:
      - .textlintrc
languages:
  markdown:
    - <<: *text-textlint
  tex:
    - <<: *text-textlint
