
[theme]
theme = "native"
[theme.overrides]
idle_fg = "#32cd32"
good_fg = "#32cd32"
info_fg = "#32cd32"
warning_fg = "#ffc107"
critical_fg = "#f44336"

[icons]
icons = "awesome6"
[icons.overrides]
cpu = "\uf463" # "\uf4bc"
memory_mem = "\ue266"
disk_drive = "\uf472"
time = "\ue385"
cogs = "\uf252" # load average
net_wired = "\uf0e8"


[[block]]
block = "music"
format = " $icon {$combo.str(max_w:20,rot_interval:1.0) $prev $play $next |}"

[[block]]
block = "cpu"
format = " $icon $utilization "
interval = 5

[[block]]
block = "memory"
format = " $icon $mem_used.eng(p:G, hide_prefix:true, hide_unit:true) /$mem_total.eng(p:G) "

# [[block]]
# block = "memory"
# format = " swap $swap_used_percents.eng(w:2) "
# format_alt = " swap $swap_used.eng(p:G, hide_prefix:true, hide_unit:true) /$swap_total.eng(p:G) "

# [[block]]
# block = "disk_space"
# path = "/"
# info_type = "available"
# format = " $icon $available.eng(w:4) ($total) "
# interval = 60
# warning = 30.0
# alert = 10.0

[[block]]
block = "load"
format = " $icon $1m.eng(w:4) "

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $frequency|Wired} ^icon_net_up$speed_up.eng(prefix:K, w:4) ^icon_net_down$speed_down.eng(prefix:K, w:4) "
interval = 5
[[block.click]]
button = "left"
cmd = "nm-connection-editor"

[[block]]
block = "battery"
interval = 60
format = " $icon $percentage "
missing_format = ""

[[block]]
block = "sound"
step_width = 5
format = " $icon $volume.eng(w:2) "
[[block.click]]
button = "left"
cmd = "pactl set-sink-mute @DEFAULT_SINK@ toggle"

[[block]]
block = "time"
interval = 60
[block.format]
full = " $icon $timestamp.datetime(f:'%Y-%m-%d(%a) %H:%M') "
