[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
hi DiffChange ctermbg=33
'''

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'bkad/CamelCaseMotion'
hook_add = '''
map <silent> W <Plug>CamelCaseMotion_w
map <silent> B <Plug>CamelCaseMotion_b
map <silent> E <Plug>CamelCaseMotion_e
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
nmap <Space>g [Git]
nnoremap [Git]a :<C-u>Gwrite<CR>
nnoremap [Git]c :<C-u>Git commit -m ""<Left>
nnoremap [Git]b :<C-u>Git blame<CR>
nnoremap [Git]l :<C-u>Git log<CR>
nnoremap [Git]s :<C-u>Git<CR>
nnoremap [Git]p :<C-u>Git push<CR>
nnoremap [Git]d :<C-u>Gdiff<CR>
nnoremap [Git]r :<C-u>Gread<CR>
nnoremap [Git]g :<C-u>Ggrep<Space>
'''


[[plugins]]
repo = 'kana/vim-textobj-user'
[[plugins]]
repo = 'sgur/vim-textobj-parameter'
[[plugins]]
repo = 'machakann/vim-textobj-functioncall'

[[plugins]]
repo = "mattn/vim-sonictemplate"
hook_add = '''
let g:sonictemplate_vim_template_dir = '$HOME/.vim/templates'
'''

[[plugins]]
repo = "github/copilot.vim"

# [[plugins]]
# repo = 'dstein64/vim-startuptime'

