

[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim', 'pum.vim']
on_event = ['InsertEnter']

hook_source = '''

call ddc#custom#patch_global('sources', ['ultisnips', 'file', 'around'])
call ddc#custom#patch_global('sourceOptions', {
\	'_': {
\		'ignoreCase': v:true,
\		'matchers': ['matcher_head'],
\		'minAutoCompleteLength': 2,
\		'sorters' : ['sorter_rank'],
\	},
\	'around': {
\		'mark': 'A',
\		'maxItems': 5,
\	},
\	'vim-lsp': {
\		'mark': 'LSP',
\		'isVolatile': v:true,
\		'forceCompletionPattern': '\.\w*|:\w*|->\w*',
\		'matchers': ['matcher_head'],
\		'maxItems': 5,
\	},
\	'file': {
\		'mark': 'F',
\		'isVolatile': v:true,
\		'minAutoCompleteLength': 3,
\		'forceCompletionPattern': '\S/\S*',
\	},
\	'ultisnips': {
\		'mark': 'S',
\		'keywordPattern': '[a-zA-Z_\\\[\]<>\*]+',
\		'isVolatile': v:true,
\		'minAutoCompleteLength': 2,
\	},
\})


call ddc#custom#patch_filetype(
\	['python', 'rust', 'typescript', 'go', 'c', 'cpp'], 
\	'sources', ['ultisnips', 'file', 'vim-lsp', 'around']
\)

call ddc#custom#patch_global('ui', 'pum')
call ddc#custom#patch_global('backspaceCompletion', v:true)
call ddc#enable()
'''


[[plugins]]
repo = 'Shougo/pum.vim'
depends = ['ddc.vim', 'ultisnips', 'lexima.vim']
on_source = ['ddc.vim']
hook_post_source = '''
inoremap <expr> <Tab> pum#visible() ? "<CMD>call pum#map#insert_relative(+1)<CR>" : "\<Tab>"
inoremap <expr> <S-Tab> pum#visible() ? "<CMD>call pum#map#insert_relative(-1)<CR>" : "\<S-Tab>"

"\!empty(UltiSnips#SnippetsInCurrentScope()) ? "<CMD>call UltiSnips#ExpandSnippet()<CR>" : 
inoremap <expr> <CR> pum#visible() ? 
\UltiSnips#CanExpandSnippet() ? "<CMD>call UltiSnips#ExpandSnippet()<CR>" : 
\"<CMD>call pum#map#confirm()<CR>" : 
\lexima#expand('<LT>CR>', 'i')

hi Pmenu ctermfg=250 ctermbg=238
'''

[[plugins]]
repo = 'Shougo/ddc-source-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-filter-matcher_head'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-filter-sorter_rank'
on_source = 'ddc.vim'

[[plugins]]
repo = 'LumaKernel/ddc-source-file'
on_source = 'ddc.vim'

[[plugins]]
repo = 'shun/ddc-source-vim-lsp'
on_source = ['ddc.vim', 'vim-lsp']


# [[plugins]]
# repo = 'LumaKernel/ddc-tabnine'
# on_source = 'ddc.vim'
#hook_add='''
# call ddc#custom#patch_global('sourceParams', {
# \	'tabnine': {
# \		'maxNumResults': 3
# \	}
# \})
#'''


[[plugins]]
repo = 'matsui54/ddc-ultisnips'
on_source = ['ddc.vim', 'ultisnips']

[[plugins]]
repo = 'Shougo/ddc-ui-pum'
on_source = ['ddc.vim', 'pum.vim']

