[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
hi DiffChange ctermbg=33
'''

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'


[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
" numToStr/Comment.nvim , preservim/nerdcommenter"
if g:wsl || has('win32')
	nmap <C-_> <Plug>(caw:hatpos:toggle)
	vmap <C-_> <Plug>(caw:hatpos:toggle)
else
	nmap <C-/> <Plug>(caw:hatpos:toggle)
	vmap <C-/> <Plug>(caw:hatpos:toggle)
endif
'''

[[plugins]]
repo = 'bkad/CamelCaseMotion'
hook_add = '''
map <silent> W <Plug>CamelCaseMotion_w
map <silent> B <Plug>CamelCaseMotion_b
map <silent> E <Plug>CamelCaseMotion_e
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
nmap <Space>g [Git]
nnoremap [Git]a :<C-u>Gwrite<CR>
nnoremap [Git]c :<C-u>Git commit -m ""<Left>
nnoremap [Git]b :<C-u>Git blame<CR>
nnoremap [Git]l :<C-u>Git log<CR>
nnoremap [Git]s :<C-u>Git<CR>
nnoremap [Git]p :<C-u>Git push<CR>
nnoremap [Git]d :<C-u>Gdiff<CR>
nnoremap [Git]r :<C-u>Gread<CR>
nnoremap [Git]g :<C-u>Ggrep<Space>
'''


[[plugins]]
repo = 't9md/vim-quickhl'
# on_if = '&readonly && &buftype ==# ""'
hook_add = '''
nmap <Space>M ^v$<Plug>(quickhl-manual-this)<ESC>

nmap <Space>mm <Plug>(quickhl-manual-this)
nmap <Space>mM <Plug>(quickhl-manual-reset)

nmap <Space>mn <Plug>(quickhl-manual-go-to-next)<SID><Space>m
nmap <Space>mN <Plug>(quickhl-manual-go-to-prev)<SID><Space>m
nnoremap <silent><script> <SID><Space>mn :<C-u>QuickhlManualGoToNext<CR><SID><Space>m
nnoremap <silent><script> <SID><Space>mN :<C-u>QuickhlManualGoToPrev<CR><SID><Space>m
nmap <SID><Space>m <Nop>
'''


[[plugins]]
repo = 'kana/vim-textobj-user'
[[plugins]]
repo = 'sgur/vim-textobj-parameter'
[[plugins]]
repo = 'machakann/vim-textobj-functioncall'


# [[plugins]]
# repo = 'dstein64/vim-startuptime'

