
[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'lambdalisue/guise.vim'

# [[plugins]]
# repo = 'skanehira/denops-silicon.vim'
# # :'<,'>Silicon out.png
# hook_source = '''
# let g:silicon_options = {
#   \   font: 'Cica',
#   \   no_line_number: v:true,
#   \   no_round_corner: v:false,
#   \   no_window_controls: v:false,
#   \   background_color: '#ffffff',
#   \   line_offset: 1,
#   \   line_pad: 2,
#   \   shadow_blur_radius: 0,
#   \   shadow_color: '#555555',
#   \   tab_width: 4,
#   \   theme: 'Solarized (dark)',
#   \ }
# '''

# [[plugins]]
# repo = 'uga-rosa/scorpeon.vim'
# on_cmd = 'VsctmHighlightEnable'
# depends = 'denops.vim'
# hook_source = '''
# '''


[[plugins]]
repo = 'gamoutatsumi/dps-ghosttext.vim'
# :GhostStart
