# `sheldon` configuration file
# ----------------------------

shell = "zsh"

[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
defer = "{{ hooks | get: \"pre\" | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks | get: \"post\" | nl }}"
# install_sh = "if [ ! -x \"$(command -v {{ name }})\" ]; then {{ dir }}/install.sh; fi"

# [plugins.zsh-autocomplete]
# github = "marlonrichert/zsh-autocomplete"
# [plugins.zsh-autocomplete.hooks]
# pre = "source $ZDOTDIR/pluginconf/zsh-autocomplete_pre.zsh"
# post = "source $ZDOTDIR/pluginconf/zsh-autocomplete_post.zsh"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]
apply = ["defer"]
[plugins.zsh-autosuggestions.hooks]
post = "source $ZDOTDIR/pluginconf/zsh-autosuggestions_post.zsh"


[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
use = ["{{ name }}.zsh"]
apply = ["defer"]


[plugins.zoxide]
github = "ajeetdsouza/zoxide"
apply = ["defer"]
