live_config_reload = true
[shell]
program = "/usr/bin/zsh"
args = ["-l"]

[font]
size = 14.0
[font.bold]
family = "Cica"
style = "Bold"
[font.bold_italic]
family = "Cica"
style = "Bold Ialic"
[font.italic]
family = "Cica"
style = "Italic"
[font.normal]
family = "Cica"
style = "Regular"

[window]
opacity = 0.5
