#!/bin/bash

prohibit_files=(
	^zsh/localconf/.*
)

isContains () {
	local e
	for e in "${@:2}"; do [[ "$1" =~ $e ]] && return 0; done
	return 1
}

for FILE in `git diff --cached --name-status $against -- | cut -c3-`; do
	if isContains $FILE "${prohibit_files[@]}"; then
		echo "$FILE"
		CHANGE_PROHIBIT=1
	fi
done

if [ "$CHANGE_PROHIBIT" ]; then
	echo "Failed to commit because of modificate local_file."
	exit 1
fi
